import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import {
  faCloudflare,
  faCss3Alt,
  faDebian,
  faDocker,
  faGitAlt,
  faHtml5,
  faJs,
  faLaravel,
  faLinux,
  faPhp,
  faReact,
  faWindows,
} from '@fortawesome/free-brands-svg-icons'
import {
  faCloud,
  faChartLine,
  faCode,
  faDatabase,
  faDesktop,
  faHeadset,
  faMagnifyingGlass,
  faNetworkWired,
  faPhone,
  faRoute,
  faServer,
  faTerminal,
  faTicket,
  faTowerBroadcast,
  faRobot,
  faShieldHalved,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

const technologyIcons: Record<string, IconDefinition> = {
  PHP: faPhp,
  Laravel: faLaravel,
  Livewire: faTowerBroadcast,
  SQL: faDatabase,
  MySQL: faDatabase,
  JavaScript: faJs,
  React: faReact,
  TypeScript: faCode,
  HTML: faHtml5,
  CSS: faCss3Alt,
  'Vanilla CSS': faCss3Alt,
  Git: faGitAlt,
  Debian: faDebian,
  'Debian 13': faDebian,
  Linux: faLinux,
  VPS: faServer,
  Shell: faTerminal,
  Bash: faTerminal,
  Nginx: faServer,
  'Docker-Grundlagen': faDocker,
  Cloudflare: faCloudflare,
  Nextcloud: faCloud,
  Guacamole: faDesktop,
  Cloudron: faCloud,
  CloudPanel: faServer,
  DNS: faRoute,
  'TCP/IP-Grundlagen': faNetworkWired,
  Router: faRoute,
  Switches: faNetworkWired,
  VPN: faNetworkWired,
  'VPN-Grundlagen': faNetworkWired,
  WireGuard: faNetworkWired,
  'Reverse Proxy': faServer,
  'Virtuelle Netzwerke': faNetworkWired,
  Firewall: faShieldHalved,
  'Pi-hole': faShieldHalved,
  OpenVPN: faNetworkWired,
  VMs: faDesktop,
  Ticketsysteme: faTicket,
  Geräteeinrichtung: faDesktop,
  'Windows-Domänen': faWindows,
  'Active Directory / Windows-Domänen': faWindows,
  Fehleranalyse: faMagnifyingGlass,
  Kundensupport: faHeadset,
  VoIP: faPhone,
  'Cloud PBX': faCloud,
  Blade: faCode,
  Vite: faCode,
  Hyprland: faDesktop,
  'KDE Plasma': faDesktop,
  X11: faDesktop,
  Wayland: faDesktop,
  Dotfiles: faCode,
  'Oh My Posh': faTerminal,
  Fastfetch: faTerminal,
  Docker: faDocker,
  Prometheus: faServer,
  Grafana: faChartLine,
  Ollama: faRobot,
  'Open WebUI': faRobot,
  n8n: faNetworkWired,
  Langflow: faRoute,
}

type TechnologyIconProps = {
  name: string
}

export function TechnologyIcon({ name }: TechnologyIconProps) {
  const icon = technologyIcons[name] ?? faCode

  return <FontAwesomeIcon className="tag-list__icon" icon={icon} aria-hidden="true" />
}
